# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c80803993719906b7755460c0ffa923ad28a94add3c4588112856d6c5a28bcbb17392badc2c197fd0f9083d140c8b460b0c504c568a038d422de71a40e78c49

test:
  secret_key_base: 4dbece86e5c7f08dacb0ac0c22dfedb2899ee97f2d1b71dc1cfaa086e24fe4eabde447cbae17a30094943162c491bddb1fb7487032994c09b0c92e650b26e4ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
