# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Product.create(:name => "Alamosaurus", :description => "Alamosaurus is a genus of titanosaurian sauropod dinosaurs, containing a single known species, Alamosaurus sanjuanensis, from the late Cretaceous Period of what is now southern North America. Isolated vertebrae and limb bones indicate that it reached sizes comparable to Argentinosaurus and Puertasaurus, which would make it the largest dinosaur known from North America.[2] Its fossils have been recovered from a variety of rock formations spanning the Maastrichtian age of the late Cretaceous period. Specimens of a juvenile Alamosaurus sanjuanensis have been recovered from only a few meters below the Cretaceous-Paleogene boundary in Texas, making it among the last surviving non-avian dinosaur species.", :image_url => "Alamosaurus_sanjuanensis_dinosaur_resize.jpg", :colour => "Reddish-Brown", :price => 3259.06)
Product.create(:name => "Aucasaurus", :description => "Aucasaurus was a genus of medium-sized theropod dinosaur from Argentina that lived during the Santonian - Campanian stage of the Anacleto Formation. It was smaller than the related Carnotaurus, although more derived in some ways, such as its extremely reduced arms and almost total lack of fingers. The type skeleton is complete to the thirteenth caudal vertebra, and so is relatively well understood, and is the most complete abelisaurid yet described. However, the skull is damaged, causing some paleontologists to speculate that it was involved in a fight prior to death.", :image_url => "Aucasaurus_dinosaur_resize.jpg", :colour => "Reddish-Brown", :price => 2498.52)
Product.create(:name => "Edmontonia", :description => "Edmontonia was an armoured dinosaur, part of the nodosaur family from the Late Cretaceous Period. It is named after the Edmonton Formation (now the Horseshoe Canyon Formation in Canada), the unit of rock it was found in.", :image_url => "Edmontonia_dinosaur_resize.jpg", :colour => "Light Green and Beige", :price => 4987.03)
Product.create(:name => "Megalosaurus", :description => "Megalosaurus is a genus of large meat-eating theropod dinosaurs of the Middle Jurassic period (Bathonian stage, 166 million years ago) of Southern England. Although fossils from other areas have been assigned to the genus, the only certain remains of Megalosaurus come from Oxfordshire and date to the late Middle Jurassic.", :image_url => "Megalosaurus_dinosaur_resize.jpg", :colour => "Reddish-Brown and Spotted", :price => 3169.87)
Product.create(:name => "Nanshiungosaurus", :description => "Nanshiungosaurus is a genus of therizinosaurian theropod dinosaur from the Cretaceous of China. Two species have been named in the genus: the type species Nanshiungosaurus brevispinus and Nanshiungosaurus bohlini.", :image_url => "Nanshiungosaurus_dinosaur_resize.jpg", :colour => "Copper, White, Black, and Beige", :price => 8234.78)
Product.create(:name => "Nanyangosaurus", :description => "Nanyangosaurus is a genus of herbivorous ornithischian dinosaur from the Early Cretaceous. It was an iguanodont which lived in the area of present-day China. It was a rather small euornithpod with an estimated length of four to five metres. The length of the femur is 517 millimetres. The forelimbs were relatively long with a long hand. The first digit of the hand was completely absent including the first metacarpal; according to the describers this was not an accident of preservation but the actual condition of the living animal. The species would then not have possessed the thumb spike typical of its relatives.", :image_url => "Nanyangosaurus_dinosaur_resize.jpg", :colour => "Copper and Light Green", :price => 9568.12)
Product.create(:name => "Saltasaurus", :description => "Saltasaurus (which means 'lizard from Salta') is a genus of titanosaurid sauropod dinosaur of the Late Cretaceous Period of Argentina. Small among sauropods, though still heavy by the standards of modern creatures, Saltasaurus was characterized by a short neck and stubby limbs. It was the first genus of sauropod known to possess armour of bony plates embedded in its skin. Such small bony plates, called osteoderms, have since been found on other titanosaurids.", :image_url => "Saltasaurus_dinosaur_resize.jpg", :colour => "Sandy Beige", :price => 10267.08)
Product.create(:name => "Supersaurus", :description => "Supersaurus (meaning 'super lizard') is a genus of diplodocid sauropod dinosaur first discovered by Vivian Jones of Delta, Colorado, in late Jurassic period rocks of the middle Morrison Formation of Colorado in 1972, and later in Portugal under the name S. lourinhanensis. The fossil remains came from the Brushy Basin Member of the formation, dating to about 153 million years ago.", :image_url => "Supersaurus_dinosaur_resize.jpg", :colour => "Pale Dark Green and Blue", :price => 25894.25)